version: "3"
services:
  server:
    build: server/
    command: python ./app.py
    ports:
      - 5000:5000
  client:
    build: client/
    command: python ./app.py
    ports:
      - 3000:3000
    depends_on:
      - server